name: add-label
on: [pull_request]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: add PR labels
        run: |
          if [ $GITHUB_BASE_REF = 'develop' ]; then
            PR_NUM=`echo $GITHUB_REF | sed -e 's/[^0-9]//g'`
            gh issue edit $PR_NUM --add-label "unmerged,unmerged-cc"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
